### ISSUE TITLE
make repo structure sane

### ISSUE THREAD

**Issue by zabbal** [sklprogs/mclient#1]
wtf are all the date folders? Learn how version control works and make repo structure normal way - like everybody does.

**Comment by sklprogs** [comment]
Is it better?

**Comment by zabbal** [comment]
Sweet, thank you!

**Comment by zabbal** [comment]
On a related note - if the old repo structure is not an artefact of heavy drinking but attempt to track releases than you might want to read this: https://github.com/blog/1547-release-your-software and something about 'git tag' command.

**Comment by sklprogs** [comment]
> This would also help to remove build/*.7z

No, I need to distribute a windows binary as well. Where should I put it then?

**Comment by zabbal** [comment]
Just follow the instructions in https://github.com/blog/1547-release-your-software - it doesn't have to clutter your repo.
