### ISSUE TITLE
Working together?

### ISSUE THREAD

**Issue by scrapix** [sklprogs/mclient#1]
Hey, I just found your mclient. Not sure what it does exactly since the readme file is very short. 

Just recently started to develop a multitran cli (while I'm not a developer)

Do you want to have a look at this project? https://github.com/scrapix/multitran_cli 
If you think it fits to yours - maybe we can work together? I think you are much better programmer. 
I can do everything about design (UX/UI/Animation)!

Если что, и по русский можно.

**Comment by sklprogs** [comment]
Hi! Please take a look at [PDF in English](https://github.com/sklprogs/mclient/raw/main/docs/README-EN.pdf) or [PDF in Russian](https://github.com/sklprogs/mclient/raw/main/docs/README-RU.pdf). This manual will help you to set up the program and use it.

I'll take a look at your code.

If you are a UI expert... well, I'd love to have a table-like QT GUI, say, using QTextTable or QTableWidget.

Что касается языка. Пишите на том, который лучше знаете, я свободно владею обоими.

**Comment by sklprogs** [comment]
Closed due to inactivity.
