### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by dikonov** [sklprogs/mclient#2]
Пробую запустить и получаю жалобы на модули питона
$ ./mclient.pyw
Traceback (most recent call last):
  File "./mclient.pyw", line 9, in <module>
    import tkinter as tk
ImportError: No module named 'tkinter'

bash-3.2$ sudo apt-get install tkinter
Чтение списков пакетов... Завершено
Построение дерева зависимостей... Завершено
Выбрано python-modules-tkinter для 'tkinter'
Последняя версия python-modules-tkinter уже установлена.
0 будет обновлено, 0 новых установлено, 0 пакетов будет удалено и 7 не будет обновлено.
bash-3.2$ rpm -q python-modules-tkinter
python-modules-tkinter-2.7.8-alt1

Нельзя ли подробно написать, какие версии каких модулей и какого питона нужны этому скрипту и как его собирать (для тех, кто в перле)?

**Comment by sklprogs** [comment]
Это скрипт для запуска в Python 3, а в у Вас Python 2. Нужен Python 3 и пакет python3-tk, а также следующие модули: sys, os, time, re, codecs, webbrowser, tkinter, tkinter.messagebox, urllib, html.parser, posixpath, configparser. Модули ищите на https://pypi.python.org, а под windows - еще на http://www.lfd.uci.edu/~gohlke/pythonlibs/. Версии я брал последние. Для запуска потребуется main.cfg, который есть в бинарных сборках linux.7z или windows.7z. Другие детали запуска есть в руководстве по программе.
