### ISSUE TITLE
windows - похоже, не запоминает последние размеры и позицию окна

### ISSUE THREAD

**Issue by SHPundit** [sklprogs/mclient#3]
Хорошо бы сделать запоминание последней позиции и размеров окна, Либо объяснить, как это включить, если уже сделано.

Спасибо за проект - несмотря на аляповатость интерфейса, пользоваться намного удобнее, чем через браузер.

**Comment by sklprogs** [comment]
1. Укажите свою ОС
2. Укажите порядок действий, при которых позиция и размеры не запоминаются (например, уменьшить окно, переместить, свернуть, нажать Alt-Tab).
3. Что конкретно не нравится в интерфейсе?

**Comment by sklprogs** [comment]
Вернул старую логику управления окнами. Перекачайте релиз.
