### ISSUE TITLE
Broken symbolic links in the repository

### ISSUE THREAD

**Issue by opennota** [sklprogs/mclient#4]
The `src` directory contains symbolic links to `/usr/local/bin/shared/src/shared.py` and `/usr/local/bin/shared/src/sharedGUI.py`. I don't have these files on my machine => I can't start the program.

**Comment by sklprogs** [comment]
I haven't managed git submodules yet, sorry. You can find necessary files here: https://github.com/sklprogs/shared

**Comment by opennota** [comment]
Yes, with the provided files I was able to start the program.

**Comment by sklprogs** [comment]
Replaced symlinks with hard links. Should do the trick (at least, temporarily).
